### ISSUE TITLE
Can't open , bro~

### ISSUE THREAD

**Issue by gaox-dev** [MajiaTools/MajiaTools#2]
Can't open ,and I have tried codesigner deep. Still don't
work~

**Comment by MajiaTools** [comment]
麻烦看文档.使用请必看

**Comment by gaox-dev** [comment]
![截屏2019-10-22上午10 06 33](https://user-images.githubusercontent.com/38782198/67255274-d4eaed00-f4b3-11e9-8a00-74d1daefc0d4.png)
just stuck this screen

**Comment by MajiaTools** [comment]
由于防火墙的原因,不是内地用户的话,暂时注册访问不了

**Comment by gaox-dev** [comment]
10.14 可以使用
10.15 无法打开~

**Comment by MajiaTools** [comment]
![411199A537906F1F8C2F33814CB6C827](https://user-images.githubusercontent.com/55486893/67258165-e804b980-f4c1-11e9-9dbe-eb19d2f583f2.jpg)10.15的在这勾选权限试试

**Comment by gaox-dev** [comment]
10.15 勾选没用..依旧打不开;
10.14 闪退

**Comment by gaox-dev** [comment]
close
